cocktail_profi/bar/urls.py
from django.urls import path

from bar import views

app_name = 'bar'

urlpatterns = [
    path('', views.my_bar_view, name='index'),
    path('add/<int:ingredient_id>/', views.add_ingredient, name='add'),
    path('match/', views.cocktail_match_view, name='match'),
    path('remove/<int:ingredient_id>/', views.remove_ingredient, name='remove')
]

cocktail_profi/catalog/urls.py
from django.urls import path

from catalog import views

app_name = 'catalog'

urlpatterns = [
    path('', views.cocktails_list, name='home'),
    path(
        'cocktail/<int:cocktail_id>/',
        views.cocktail_detail,
        name='cocktail_detail'
    ),
    path('category/', views.categories_list, name='categories_list'),
    path(
        'category/<int:category_id>/',
        views.cocktails_by_category,
        name='category_cocktails'
    ),
    path(
        'toggle_like_cocktail/<int:cocktail_id>/',
        views.toggle_like_cocktail,
        name='toggle_like_cocktail'
    ),
    path('favorite_cocktails/', views.favorite_cocktails, name='favorite')
]

cocktail_profi/cocktail_profi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('auth/', include('users.urls')),
    path('bar/', include('bar.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

cocktail_profi/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='users/login.html'
    ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='users/logout.html'
    ), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup')
]

cocktail_profi/templates/includes/cocktail_card.html
<div class="card" style="width: 20rem; height: 470px">
  <img src="{{ cocktail.image_url }}" class="card-img-top" alt="{{ cocktail.name }}">
  <div class="card-body">
    <h6 class="card-subtitle mb-2 text-muted">
      <a href="{% url 'catalog:category_cocktails' cocktail.category.id %}" class="text-decoration-none text-reset">
        {{ cocktail.category.name_ru }}
      </a>
    </h6>
    <h5 class="card-title">{{ cocktail.name }}</h5>
    <a href="{% url 'catalog:cocktail_detail' cocktail.id %}" class="btn btn-primary">Подробнее</a>
    {% if user.is_authenticated %}
      <a href="{% url 'catalog:toggle_like_cocktail' cocktail.id %}" 
        class="btn {% if cocktail.id in favorite_cocktails %}btn-danger{% else %}btn-outline-danger{% endif %} text-nowrap">
        {% if cocktail.id in favorite_cocktails %}
          В избранном
        {% else %}
          В избранное
        {% endif %}
      </a>
    {% endif %}
  </div>
</div>

cocktail_profi/templates/includes/footer.html
{% load static %}
<footer class="pt-5 pb-3 mt-5 bg-light border-top">
  <div class="container">
      <div class="row">
        <div class="col-md-5 mb-3">
          <h5>
            <img src="{% static 'img/favicon_32x32.svg' %}" style="margin-top:-10px; width:40px">
            Cocktail Profi
          </h5>
          <p class="text-muted small">
              Интерактивный справочник бармена. 
              Учебный проект, разработанный на Django. 
              Все рецепты взяты из открытых источников.
          </p>
        </div>
        <div class="col-md-3 mb-3">
          <h5>Разделы</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2">
              <a href="{% url 'catalog:home' %}" class="nav-link p-0 text-muted">Главная</a>
            </li>
            <li class="nav-item mb-2">
              <a href="{% url 'catalog:categories_list' %}" class="nav-link p-0 text-muted">Категории</a>
            </li>
            <li class="nav-item mb-2">
              <a href="{% url 'bar:index' %}" class="nav-link p-0 text-muted">Мой бар</a>
            </li>
            <li class="nav-item mb-2">
              <a href="{% url 'catalog:favorite' %}" class="nav-link p-0 text-muted">Избранное</a>
            </li>
          </ul>
        </div>
        <div class="col-md-4 mb-3">
          <h5>Разработчик</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2">
              <span class="text-muted">Студент: Власова Софья</span>
            </li>
            <li class="nav-item mb-2">
              <a href="https://github.com/sonixks/cocktail-profi" target="_blank" class="nav-link p-0 text-primary">
                GitHub Репозиторий
              </a>
            </li>
          </ul>
        </div>
    </div>
    <div class="d-flex flex-column flex-sm-row justify-content-center py-4 my-4 border-top">
      <p class="text-danger fw-bold text-uppercase text-center" style="letter-spacing: 1px;">
        Чрезмерное употребление алкоголя вредит вашему здоровью (18+)
      </p>
    </div>
  </div>
</footer>

cocktail_profi/templates/includes/header.html
{% load static %}
<header class="p-3 bg-white border-bottom shadow-sm">
  <div class="container">
    <div class="d-flex justify-content-lg-start align-items-center">
      <a href="{% url 'catalog:home' %}" class="text-dark text-decoration-none me-4">
        <span class="fs-4 fw-bold">
          <img src="{% static 'img/favicon_32x32.svg' %}" style="margin-top:-10px; width:32px">
          Cocktail Profi
        </span>
      </a>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'catalog:home' %}" class="nav-link px-2 link-dark">Главная</a></li>
        <li><a href="{% url 'catalog:categories_list' %}" class="nav-link px-2 link-dark">Категории</a></li>
        <li><a href="{% url 'bar:index' %}" class="nav-link px-2 link-dark">Мой бар</a></li>
        <li><a href="{% url 'catalog:favorite' %}" class="nav-link px-2 link-dark">Избранное</a></li>
      </ul>
      <div class="text-end">
        {% if user.is_authenticated %}
          <span class="me-3 text-muted">Привет, <b>{{ user.username }}</b>!</span>
          <form action="{% url 'users:logout' %}" method="post" class="d-inline">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-danger btn-sm">Выход</button>
          </form>
        {% else %}
          <a href="{% url 'users:login' %}" class="btn btn-outline-primary me-2">Вход</a>
          <a href="{% url 'users:signup' %}" class="btn btn-primary">Регистрация</a>
        {% endif %}
      </div>
    </div>
  </div>
</header>

cocktail_profi/templates/includes/search.html
<form class="d-flex" method="GET">
  <input class="form-control me-2" type="search" placeholder="Название коктейля" aria-label="Search" name="search_query" required>
  <button class="btn btn-outline-success" type="submit">Найти</button>
</form>