cocktail_profi/bar/urls.py
from django.urls import path

from bar import views

app_name = 'bar'

urlpatterns = [
    path('', views.my_bar_view, name='index'),
    path('add/<int:ingredient_id>/', views.add_ingredient, name='add'),
    path('match/', views.cocktail_match_view, name='match'),
    path('remove/<int:ingredient_id>/', views.remove_ingredient, name='remove')
]

cocktail_profi/catalog/urls.py
from django.urls import path

from catalog import views

app_name = 'catalog'

urlpatterns = [
    path('', views.cocktails_list, name='home'),
    path(
        'cocktail/<int:cocktail_id>/',
        views.cocktail_detail,
        name='cocktail_detail'
    ),
    path('category/', views.categories_list, name='categories_list'),
    path(
        'category/<int:category_id>/',
        views.cocktails_by_category,
        name='category_cocktails'
    ),
    path(
        'toggle_like_cocktail/<int:cocktail_id>/',
        views.toggle_like_cocktail,
        name='toggle_like_cocktail'
    ),
    path('favorite_cocktails/', views.favorite_cocktails, name='favorite')
]

cocktail_profi/cocktail_profi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('auth/', include('users.urls')),
    path('bar/', include('bar.urls'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

cocktail_profi/catalog/models.py
from django.db import models
from django.contrib.auth import get_user_model


class MeasurementUnit(models.Model):
    name_en = models.CharField(
        max_length=50,
        unique=True,
        verbose_name="Ед. изм. (EN)"
    )
    name_ru = models.CharField(max_length=50, verbose_name="Ед. изм. (RU)")

    class Meta:
        verbose_name = 'единица измерения'
        verbose_name_plural = 'Единицы измерения'

    def __str__(self):
        return f"{self.name_en} -> {self.name_ru}"


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    name_ru = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Ingredient(models.Model):
    name = models.CharField(max_length=100, unique=True)
    name_ru = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'ингредиент'
        verbose_name_plural = 'Ингредиенты'

    def __str__(self):
        return self.name


class Cocktail(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    name_ru = models.CharField(max_length=200)
    instruction = models.TextField()
    instruction_ru = models.TextField()
    is_alcoholic = models.BooleanField(default=True)
    is_published = models.BooleanField(default=True)
    image_url = models.URLField(blank=True, null=True)
    external_id = models.CharField(max_length=50, unique=True)

    class Meta:
        ordering = ('-id',)
        verbose_name = 'коктейль'
        verbose_name_plural = 'Коктейли'

    def __str__(self):
        return self.name


class CocktailIngredient(models.Model):
    cocktail = models.ForeignKey(Cocktail, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    amount = models.CharField(max_length=100, blank=True, null=True)


class Favourite(models.Model):
    User = get_user_model()
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='favorites'
    )
    cocktail = models.ForeignKey(Cocktail, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'cocktail')

cocktail_profi/catalog/views.py
import random

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import get_object_or_404, render, redirect

from catalog.models import Category, Cocktail, Favourite


@login_required
def toggle_like_cocktail(request, cocktail_id):
    cocktail_obj = get_object_or_404(Cocktail, id=cocktail_id)
    favourite, created = Favourite.objects.get_or_create(
        user=request.user,
        cocktail=cocktail_obj
    )

    if not created:
        favourite.delete()
    return redirect(request.META.get('HTTP_REFERER', 'catalog:home'))


def get_published_cocktails():
    result = Cocktail.objects.select_related(
        'category',
        ).filter(
            is_published=True
        )
    return result


def get_random_cocktails(cocktails_list, cocktails_number):
    cocktails_list = list(cocktails_list)
    return random.sample(cocktails_list, cocktails_number)


def cocktails_list(request):
    template = 'catalog/cocktails_list.html'
    cocktails_list = get_published_cocktails()
    if request.GET:
        sub_string = request.GET.get('search_query')
        if sub_string is not None and not sub_string.strip():
            return redirect('catalog:home')
        cocktails = cocktails_list.filter(
            Q(name__icontains=sub_string) |
            Q(name_ru__icontains=sub_string) |
            Q(name_ru__icontains=sub_string.capitalize())
        )
    else:
        cocktails = get_random_cocktails(cocktails_list, 24)
    favorite_cocktails = []
    if request.user.is_authenticated:
        favorite_cocktails = request.user.favorites.values_list(
            'cocktail_id',
            flat=True
        )
    context = {
        'cocktails_list': cocktails,
        'favorite_cocktails': favorite_cocktails
    }
    return render(request, template, context)


def get_favotite_cocktails(request):
    favorite_cocktails = []
    if request.user.is_authenticated:
        favorite_cocktails = request.user.favorites.values_list(
            'cocktail_id',
            flat=True
        )
    return favorite_cocktails


def cocktail_detail(request, cocktail_id):
    template = 'catalog/cocktail_detail.html'
    cocktail = get_object_or_404(get_published_cocktails().filter(
        id=cocktail_id
    ))
    favorite_cocktails = get_favotite_cocktails(request)
    context = {
        'cocktail': cocktail,
        'favorite_cocktails': favorite_cocktails
    }
    return render(request, template, context)


def categories_list(request):
    template = 'catalog/categories_list.html'
    categories = Category.objects.all().order_by('name_ru')
    context = {
        'categories': categories
    }
    return render(request, template, context)


def cocktails_by_category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    cocktails = get_published_cocktails().filter(
        category=category
    )
    template = 'catalog/cocktails_list.html'
    favorite_cocktails = get_favotite_cocktails(request)
    context = {
        'category': category,
        'cocktails_list': cocktails,
        'favorite_cocktails': favorite_cocktails
    }
    return render(request, template, context)


@login_required
def favorite_cocktails(request):
    template = 'catalog/cocktails_list.html'
    favorite_cocktails = get_favotite_cocktails(request)
    cocktails = get_published_cocktails().filter(
        id__in=favorite_cocktails
    )

    context = {
        'cocktails_list': cocktails,
        'favorite_cocktails': favorite_cocktails
    }
    return render(request, template, context)

cocktail_profi/templates/catalog/categories_list.html
{% extends "base.html" %}
{% block title %}Категории напитков{% endblock title %}
{% block content %}
  <h1 class="mb-4">Категории коктейлей</h1>
  <div class="list-group">
    {% for category in categories %}
      <a href="{% url 'catalog:category_cocktails' category.id %}" class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
        {{ category.name_ru }}
        <span class="badge bg-primary rounded-pill">
          {{ category.cocktail_set.count }}
        </span>
      </a>
    {% endfor %}
  </div>
{% endblock content %}

cocktail_profi/templates/catalog/cocktail_detail.html
{% extends "base.html" %}
{% block title %}{{ cocktail.name }}{% endblock title %}
{% block content %}
<div class="container">
  <div class="row justify-content-around">
    <div class="col-4">
      <h2>{{ cocktail.name }}</h2>
      <p>{{cocktail.instruction_ru}}</p>
      <ul>
        {% for ingredient in cocktail.cocktailingredient_set.all %}
          <li>{{ ingredient.ingredient.name_ru }}
            {% if ingredient.amount %}
              — <b>{{ ingredient.amount }}</b>
            {% endif %}
          </li>
        {% endfor %}
      </ul>
      {% if user.is_authenticated %}
        <a href="{% url 'catalog:toggle_like_cocktail' cocktail.id %}" 
          class="btn {% if cocktail.id in favorite_cocktails %}btn-danger{% else %}btn-outline-danger{% endif %} text-nowrap">
          {% if cocktail.id in favorite_cocktails %}
            В избранном
          {% else %}
            В избранное
          {% endif %}
        </a>
      {% endif %}
    </div>
    <div class="col-4">
      <img src={{ cocktail.image_url }} height='400' width='400'>
    </div>
  </div>
</div>
{% endblock content %}

cocktail_profi/templates/catalog/cocktails_list.html
{% extends "base.html" %}
{% block title %}Каталог коктейлей{% endblock title %}
{% block content %}
{% if request.resolver_match.url_name == 'home' %}
  <div class="mb-3">
    {% include "includes/search.html" %}
  </div>
{% endif %}
<div class="row">
  {% for cocktail in cocktails_list%}
  <div class="col-md-3 mb-3">
    {% include 'includes/cocktail_card.html' %}
  </div>
  {% endfor %}
</div>
{% endblock %}